CREATE TABLE JM3190309_OTO_UNI_STUDENT_DETAIL(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
COLLEGE_NAME VARCHAR
);

CREATE TABLE JM3190309_OTO_UNI_STUDENT(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR,
STUDENT_DETAIL_ID BIGINT,
FOREIGN KEY(STUDENT_DETAIL_ID) REFERENCES JM3190309_OTO_UNI_STUDENT_DETAIL(ID)
);