CREATE TABLE JM3190309_STUDENT(ROLL_NUMBER BIGINT, NAME VARCHAR, COURSE VARCHAR, AGE NUMBER);

-- IDENTITY
CREATE TABLE JM3190309_ID_IDENTITY_STUDENT(
ROLL_NUMBER BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR,
COURSE VARCHAR,
AGE NUMBER);

-- SEQUENCE
CREATE SEQUENCE JM3190309_ID_STUDENT_SEQUENCE;
ALTER SEQUENCE JM3190309_ID_STUDENT_SEQUENCE RESTART WITH 1003;

CREATE TABLE JM3190309_ID_SEQUENCE_STUDENT(
ROLL_NUMBER BIGINT PRIMARY KEY,
NAME VARCHAR,
COURSE VARCHAR,
AGE NUMBER);

-- AUTO
DROP SEQUENCE HIBERNATE_SEQUENCE;
CREATE SEQUENCE HIBERNATE_SEQUENCE;
CREATE TABLE JM3190309_ID_AUTO_STUDENT(
ROLL_NUMBER BIGINT PRIMARY KEY,
NAME VARCHAR,
COURSE VARCHAR,
AGE NUMBER);

-- TABLE
CREATE SEQUENCE JM3190309_ID_TABLE_STUDENT_SEQUENCE;

CREATE TABLE JM3190309_ID_TABLE_ALL_SEQUENCE(
SEQ_NAME VARCHAR,
NEXT_VAL BIGINT
)

INSERT INTO JM3190309_ID_TABLE_ALL_SEQUENCE VALUES(
'JM3190309_ID_TABLE_STUDENT_SEQUENCE',
100001
)

CREATE TABLE JM3190309_ID_TABLE_STUDENT(
ROLL_NUMBER BIGINT PRIMARY KEY,
NAME VARCHAR,
COURSE VARCHAR,
AGE NUMBER);