CREATE TABLE JM3190309_OTM_BI_COURSE(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR
);

CREATE TABLE JM3190309_OTM_BI_ASSIGNMENT(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR,
COURSE_ID BIGINT,
FOREIGN KEY(COURSE_ID) REFERENCES JM3190309_OTM_BI_COURSE(ID)
);